-- Migration 009: Add post_slug column to global_post_index
-- Enables cross-region post lookup by globally unique Snowflake ID.
-- The post_slug is the Snowflake ID generated by the regional API for each post.
ALTER TABLE global_post_index 
  ADD COLUMN IF NOT EXISTS post_slug BIGINT;

-- Index for fast lookup by post_slug (used by /posts/slug/:slug endpoint)
CREATE INDEX IF NOT EXISTS idx_gpi_post_slug ON global_post_index(post_slug);

-- Backfill post_slug from author_slug for existing posts (temporary heuristic)
-- Note: Existing posts don't have post_slug. New posts will have it set correctly.
-- This is safe because post_slug is nullable.
