-- Migration 009: Add post_slug column to global_post_index
-- Enables cross-region post lookup using globally unique Snowflake IDs
--
-- Why:
--   post_id is per-cluster auto-increment, causing conflicts across regions.
--   post_slug is a globally unique Snowflake ID (machine_id + timestamp + sequence),
--   allowing any cluster to uniquely identify a post from any region.

ALTER TABLE global_post_index
  ADD COLUMN IF NOT EXISTS post_slug BIGINT DEFAULT 0;

-- Create index for fast slug-based lookups
CREATE INDEX IF NOT EXISTS idx_gpi_post_slug ON global_post_index(post_slug);

-- Backfill: existing posts without a slug get 0 (distinguishable from valid Snowflake IDs)
-- New posts will have proper Snowflake slugs generated by the application layer.
UPDATE global_post_index SET post_slug = 0 WHERE post_slug IS NULL;

-- After backfill, enforce NOT NULL to prevent future issues
ALTER TABLE global_post_index ALTER COLUMN post_slug SET NOT NULL;
